# .___        _____.__       .__  __        __________        __    ________
# |   | _____/ ____\__| ____ |__|/  |_  ____\______   \ _____/  |_  \_____  \
# |   |/    \   __\|  |/    \|  \   __\/ __ \|    |  _//  _ \   __\   _(__  <
# |   |   |  \  |  |  |   |  \  ||  | \  ___/|    |   (  <_> )  |    /       \
# |___|___|  /__|  |__|___|  /__||__|  \___  >______  /\____/|__|   /______  /
#          \/              \/              \/       \/                     \/
#
#                                                                - by IllTamer
# GitHub:
# - 前置: https://github.com/IUnlimit/perpetua
# - 本插件: https://github.com/IllTamer/infinitebot4

# 插件配置部分
#   该配置可重载
main:
  # 管理员账号列表
  admins:
    - 765743073
  # 监听的群列表
  #   bungee: true 时此配置项无效
  groups:
    - 863522624

# 数据储存方式
#   该配置仅在加载插件时读取
database:
  # 可选择的储存方式
  #   'yaml'  - 本地yaml储存，数据仅插件加载服可用
  #   'mysql' - mysql数据库储存，群组服数据互通必选
  type: 'yaml'
  config:
    mysql:
      host: 'localhost'
      port: 3306
      username: 'root'
      password: 'root'
      database: 'minecraft'

# 连接配置项
#   该配置可重载
connection:
  # 当前客户端连接名称
  #   可为空，为空时当前连接不配置名称
  #   当附属使用分布式 API 时，建议配置，配置时应确保该名称全局唯一
  name: 'ib-1'
  # perpetua webapi 配置
  webapi:
    # 进程所在域名
    host: '127.0.0.1'
    # 服务开放端口
    port: 8080
  # 通信验证 token
  #   若您在 OneBot 实现中配置了此项，请填写，否则请留空
  authorization: ''