name: InfiniteBot3
main: com.illtamer.infinite.bot.minecraft.start.bukkit.BukkitBootstrap
version: 3.2.0

author: IllTamer

load: POSTWORLD

softdepend:
  - PlaceholderAPI
  - PlayerPoints
  - Vault

commands:
  InfiniteBot3:
    aliases:
      - ib3