name: InfiniteBot4
main: com.illtamer.infinite.bot.minecraft.start.bukkit.BukkitBootstrap
version: 4.0.4-SNAPSHOT

author: IllTamer

load: POSTWORLD

softdepend:
  - PlaceholderAPI
  - PlayerPoints
  - Vault

commands:
  InfiniteBot4:
    aliases:
      - ib4